// <auto-generated />
using System;
using KobiMuhendislikTicket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KobiMuhendislikTicket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224123006_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("WarrantyEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsForAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetTenantId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.ProductTenant", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WarrantyEndDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId", "TenantId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProductTenants");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MaxConcurrentTickets")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.System.SystemParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumericKey")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Group");

                    b.ToTable("SystemParameters");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(482),
                            DataType = "String",
                            Description = "Düşük öncelik",
                            Group = "TicketPriority",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Düşük",
                            NumericKey = 1,
                            SortOrder = 1,
                            Value = "Low",
                            Value2 = "#6C757D"
                        },
                        new
                        {
                            Id = 101,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(562),
                            DataType = "String",
                            Description = "Orta öncelik",
                            Group = "TicketPriority",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Orta",
                            NumericKey = 2,
                            SortOrder = 2,
                            Value = "Medium",
                            Value2 = "#17A2B8"
                        },
                        new
                        {
                            Id = 102,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(565),
                            DataType = "String",
                            Description = "Yüksek öncelik",
                            Group = "TicketPriority",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Yüksek",
                            NumericKey = 3,
                            SortOrder = 3,
                            Value = "High",
                            Value2 = "#FD7E14"
                        },
                        new
                        {
                            Id = 103,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(567),
                            DataType = "String",
                            Description = "Kritik öncelik",
                            Group = "TicketPriority",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Kritik",
                            NumericKey = 4,
                            SortOrder = 4,
                            Value = "Critical",
                            Value2 = "#DC3545"
                        },
                        new
                        {
                            Id = 110,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(568),
                            DataType = "String",
                            Description = "Açık",
                            Group = "TicketStatus",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Açık",
                            NumericKey = 1,
                            SortOrder = 1,
                            Value = "Open",
                            Value2 = "#007BFF"
                        },
                        new
                        {
                            Id = 111,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(570),
                            DataType = "String",
                            Description = "İşleniyor",
                            Group = "TicketStatus",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "İşleniyor",
                            NumericKey = 2,
                            SortOrder = 2,
                            Value = "Processing",
                            Value2 = "#FFC107"
                        },
                        new
                        {
                            Id = 112,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(572),
                            DataType = "String",
                            Description = "Müşteri Bekleniyor",
                            Group = "TicketStatus",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Müşteri Bekleniyor",
                            NumericKey = 3,
                            SortOrder = 3,
                            Value = "WaitingForCustomer",
                            Value2 = "#6F42C1"
                        },
                        new
                        {
                            Id = 113,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(573),
                            DataType = "String",
                            Description = "Çözüldü",
                            Group = "TicketStatus",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Çözüldü",
                            NumericKey = 4,
                            SortOrder = 4,
                            Value = "Resolved",
                            Value2 = "#28A745"
                        },
                        new
                        {
                            Id = 114,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(575),
                            DataType = "String",
                            Description = "Kapandı",
                            Group = "TicketStatus",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Kapandı",
                            NumericKey = 5,
                            SortOrder = 5,
                            Value = "Closed",
                            Value2 = "#343A40"
                        },
                        new
                        {
                            Id = 120,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(576),
                            DataType = "String",
                            Description = "Admin role",
                            Group = "UserRole",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Admin",
                            NumericKey = 1,
                            SortOrder = 1,
                            Value = "Admin"
                        },
                        new
                        {
                            Id = 121,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(578),
                            DataType = "String",
                            Description = "Staff role",
                            Group = "UserRole",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Staff",
                            NumericKey = 2,
                            SortOrder = 2,
                            Value = "Staff"
                        },
                        new
                        {
                            Id = 122,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(579),
                            DataType = "String",
                            Description = "Customer role",
                            Group = "UserRole",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Customer",
                            NumericKey = 3,
                            SortOrder = 3,
                            Value = "Customer"
                        },
                        new
                        {
                            Id = 130,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(581),
                            DataType = "String",
                            Description = "Teknik Destek",
                            Group = "Department",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "TeknikDestek",
                            NumericKey = 1,
                            SortOrder = 1,
                            Value = "Teknik Destek"
                        },
                        new
                        {
                            Id = 131,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(582),
                            DataType = "String",
                            Description = "Satış",
                            Group = "Department",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Satis",
                            NumericKey = 2,
                            SortOrder = 2,
                            Value = "Satış"
                        },
                        new
                        {
                            Id = 132,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(583),
                            DataType = "String",
                            Description = "Muhasebe",
                            Group = "Department",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Muhasebe",
                            NumericKey = 3,
                            SortOrder = 3,
                            Value = "Muhasebe"
                        },
                        new
                        {
                            Id = 133,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(585),
                            DataType = "String",
                            Description = "Yönetim",
                            Group = "Department",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Yonetim",
                            NumericKey = 4,
                            SortOrder = 4,
                            Value = "Yönetim"
                        },
                        new
                        {
                            Id = 134,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(586),
                            DataType = "String",
                            Description = "Diğer",
                            Group = "Department",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "Diger",
                            NumericKey = 5,
                            SortOrder = 5,
                            Value = "Diğer"
                        },
                        new
                        {
                            Id = 200,
                            CreatedDate = new DateTime(2026, 2, 24, 15, 30, 6, 297, DateTimeKind.Unspecified).AddTicks(587),
                            DataType = "Int",
                            Description = "Varsayılan ticket limiti",
                            Group = "General",
                            IsActive = true,
                            IsDeleted = false,
                            Key = "DefaultTicketLimit",
                            NumericKey = 1,
                            SortOrder = 1,
                            Value = "15"
                        });
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TaxOffice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TaxNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TicketCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedStaffId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TenantId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdminReply")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketImages");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Asset", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Assets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Notification", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.ProductTenant", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Product", "Product")
                        .WithMany("ProductTenants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Tenant", "Tenant")
                        .WithMany("ProductTenants")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Staff", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.System.SystemParameter", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Staff", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("AssignedStaffId");

                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Tickets")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedStaff");

                    b.Navigation("Product");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketComment", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketHistory", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.TicketImage", b =>
                {
                    b.HasOne("KobiMuhendislikTicket.Domain.Entities.Ticket", "Ticket")
                        .WithMany("TicketImages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductTenants");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ProductTenants");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("KobiMuhendislikTicket.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("TicketImages");
                });
#pragma warning restore 612, 618
        }
    }
}
